name: Assign Reviewers on PR

on:
  pull_request:
    types: [opened] 

jobs:
  assign_reviewers:
    runs-on: ubuntu-latest

    steps:
     
      - name: Assign reviewers
        uses: hmarr/auto-assign-action@v2
        with:
          reviewers: 'gergo-battyanyi,krisz1321,BenjaminKovacs09,levitolnai,mezei-b-bendeguz'
          review-type: 'REQUEST_CHANGES'
         